jog_joint_node:
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

jog_frame_node:
  group_names:
    - arm
  link_names:
    - panda_link7

move_group:
  controller_list:
    - name: panda_arm_effort_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
       - panda_joint1
       - panda_joint2
       - panda_joint3
       - panda_joint4
       - panda_joint5
       - panda_joint6
       - panda_joint7
